version: '3.8'
services:
  web:
    image: php:8.2-apache
    container_name: mi_apache
    volumes:
      - ./www:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mi_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: PHPeros_db
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mi_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpass
    ports:
      - "8080:80"
    depends_on:
      - db

  wordpress:
    image: wordpress:latest
    container_name: mi_wordpress
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: userpass
      WORDPRESS_DB_NAME: PHPeros_db
    ports:
      - "8081:80"
